version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  checkoutEtTests:
    executor: node/default
    steps:
      - run: git clone https://github.com/antmayh/Labo2_backend.git
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/Labo2_backend/node_modules
          override-ci-command: npm install
      - run: npm run test
workflows:
  build:
    jobs:
      - checkoutEtTests
