version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  checkoutEtTests:
    executor: node/default
    steps:
      - run: git clone https://github.com/antmayh/Labo2_backend.git /home/circleci/project
      - run: npm install
      - run: npm run test
  integrationFrontend:
    executor: node/default
    steps:
      - run: git clone https://github.com/antmayh/Labo2_backend.git
      - run: git clone https://github.com/antmayh/Labo2_frontend.git
      - run: cd Labo2_frontend && npm install
      - run: cd Labo2_frontend && npm build
      - run: mkdir Labo2_backend/public
      - run: cp -rT Labo2_frontend/build Labo2_backend/public
      - persist_to_workspace:
          root: .
          paths:
            - 3w5-h24-tp2-backend-test1
  deploiement:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: cd Labo2_backend && ls -Rl 
    

workflows:
  build:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend

