version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  checkoutEtTests:
    executor: node/default
    steps:
      - run: git clone https://github.com/antmayh/Labo2_backend.git
      - run: cd Labo2_backend
      - run: sudo npm install
      - run: npm run test
workflows:
  build:
    jobs:
      - checkoutEtTests
